/* Kinetic Anatomy Lab food-log screen: high-density nutrition controls arranged like an athlete fuel calibration panel. */
import { useState } from "react";
import { Check, ChevronRight, Flame, Plus, Search, Utensils } from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { useLocation } from "wouter";
import { WorkflowLayout } from "@/components/workflows/WorkflowLayout";
import { trpc } from "@/lib/trpc";
import { BackendFeedback } from "@/components/feedback/BackendFeedback";

const options = [{ name: "Greek yogurt + berries", kcal: 238, p: 24, c: 26, f: 4 }, { name: "Citrus chicken grain bowl", kcal: 468, p: 42, c: 54, f: 11 }, { name: "Salted almond recovery shake", kcal: 324, p: 31, c: 32, f: 9 }];

export default function LogFood() {
  const [, setLocation] = useLocation(); const [meal, setMeal] = useState("Lunch"); const [query, setQuery] = useState(""); const [picked, setPicked] = useState(options[1]); const [saveError, setSaveError] = useState<string | null>(null);
  const saveEntry = trpc.nutrition.create.useMutation({ onMutate: () => setSaveError(null), onSuccess: () => { toast.success("Fuel entry recorded — macros recalibrated"); setLocation("/"); }, onError: () => { const message = "Fuel entry could not be secured. Check your connection, then retry."; setSaveError(message); toast.error(message); } });
  const save = () => saveEntry.mutate({ mealType: meal, label: picked.name, calories: picked.kcal, proteinGrams: picked.p, carbGrams: picked.c, fatGrams: picked.f, consumedAt: new Date() });
  return <WorkflowLayout kicker="Nutrition / live entry" title="Log your fuel" detail="Record the meal, then let FitTrack update today’s performance targets."><motion.section className="workflow-grid food-grid" variants={{ hidden: { opacity: 0, y: 14 }, visible: { opacity: 1, y: 0 } }}><div className="workflow-panel meal-picker"><span className="panel-label">Meal window</span><div className="segment-control">{["Breakfast", "Lunch", "Dinner", "Recovery"].map((item) => <button key={item} className={meal === item ? "selected" : ""} onClick={() => setMeal(item)}>{item}</button>)}</div><label className="search-field"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search foods or scan a barcode" /></label><div className="food-options">{options.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())).map((item) => <button className={picked.name === item.name ? "food-option selected" : "food-option"} onClick={() => setPicked(item)} key={item.name}><span className="food-icon"><Utensils size={16} /></span><span><b>{item.name}</b><small>{item.kcal} kcal · {item.p}g protein</small></span>{picked.name === item.name ? <Check size={16} /> : <ChevronRight size={16} />}</button>)}</div><button className="text-action" onClick={() => toast("Barcode scanner will be available with camera support")}><Plus size={15} />Add a custom food</button></div><aside className="workflow-panel fuel-summary"><div className="summary-orbit"><Flame size={22} /><span>Added fuel</span><strong>{picked.kcal}</strong><small>kcal</small></div><div className="macro-stack"><div><span>Protein</span><b>{picked.p}g</b><i style={{ width: `${Math.min(picked.p * 2.2, 100)}%` }} /></div><div><span>Carbs</span><b>{picked.c}g</b><i style={{ width: `${Math.min(picked.c * 1.4, 100)}%` }} /></div><div><span>Fats</span><b>{picked.f}g</b><i style={{ width: `${Math.min(picked.f * 4, 100)}%` }} /></div></div><div className="summary-note"><i />Target pace remains on track</div><button className="commit-button" disabled={saveEntry.isPending} onClick={save}>{saveEntry.isPending ? "Saving entry" : `Commit ${meal.toLowerCase()}`} <span>↗</span></button>{saveEntry.isPending && <BackendFeedback tone="loading" title="Secure data link" detail="Saving this fuel entry to your athlete ledger." />}{saveError && <BackendFeedback tone="error" title="Fuel entry not saved" detail={saveError} onRetry={save} />}</aside></motion.section></WorkflowLayout>;
}
